meta_product_name: "Quick Sell"
meta_title: "Quick Sell - Sell Quick, Sell Easy"
meta_description: "Quick Sell is the platform to sell and buy your items without hassle."
meta_image: "quick-sell.png"                       # should exist in `app/assets/images/`
twitter_account: "@quicksell6"   # required for Twitter Cards
